---
all:
  children: 
    windows_vms:
      hosts:
        winvm1:
          ansible_host: 10.150.65.5
          ansible_user: finopay
          ansible_password: "{{ windows_password }}"
          ansible_connection: winrm
          ansible_winrm_transport: basic
          ansible_winrm_scheme: http
          ansible_port: 5985
          ansible_winrm_server_cert_validation: ignore
        
    linux_vms:
      hosts:
        vm1:
          ansible_host: 10.150.65.4
          ansible_user: finopay
          ansible_connection: ssh
          ansible_password: "{{ linux_password }}"
          # ansible_ssh_common_args: '-o ProxyCommand="az network bastion ssh -n bastion-name -g resource-group-name --target-resource-id /subscriptions/SUB_ID/resourceGroups/RG_NAME/providers/Microsoft.Compute/virtualMachines/VM1 --auth-type password --username adminuser --only-show-command"'
